// List of companies and their careers pages for scraping
export const companies = [
  { name: "Google", careersPage: "https://careers.google.com/" },
  { name: "Microsoft", careersPage: "https://careers.microsoft.com/" },
  { name: "Meta (Facebook)", careersPage: "https://www.metacareers.com/" },
  { name: "Twitter", careersPage: "https://careers.twitter.com/" },
  { name: "Apple", careersPage: "https://www.apple.com/jobs/us/" },
  { name: "Cisco", careersPage: "https://jobs.cisco.com/" },
  { name: "LinkedIn", careersPage: "https://careers.linkedin.com/" },
  { name: "Nvidia", careersPage: "https://www.nvidia.com/en-us/about-nvidia/careers/" },
  { name: "Intel", careersPage: "https://jobs.intel.com/" },
  { name: "Dell", careersPage: "https://jobs.dell.com/" },
  { name: "HP", careersPage: "https://jobs.hp.com/" },
  { name: "IBM", careersPage: "https://www.ibm.com/employment/" },
  { name: "Oracle", careersPage: "https://www.oracle.com/corporate/careers/" },
  { name: "Salesforce", careersPage: "https://www.salesforce.com/company/careers/" },
  { name: "Adobe", careersPage: "https://adobe.wd5.myworkdayjobs.com/en-US/external_experienced" },
  { name: "ServiceNow", careersPage: "https://www.servicenow.com/careers.html" },
  { name: "SAP Labs", careersPage: "https://www.sap.com/about/careers.html" },
  { name: "Oracle Cloud (OCI)", careersPage: "https://www.oracle.com/corporate/careers/" },
  { name: "Twilio", careersPage: "https://www.twilio.com/company/jobs" },
  { name: "Red Hat", careersPage: "https://www.redhat.com/en/jobs" },
  { name: "Atlassian", careersPage: "https://www.atlassian.com/company/careers" },
  { name: "Ericsson", careersPage: "https://www.ericsson.com/en/careers" },
  { name: "Nokia", careersPage: "https://www.nokia.com/careers/" },
  { name: "Infosys", careersPage: "https://www.infosys.com/careers/" },
  { name: "Wipro", careersPage: "https://careers.wipro.com" },
  { name: "Zoho", careersPage: "https://www.zoho.com/careers/" },
  { name: "Byju's", careersPage: "https://byjus.com/careers/" },
  { name: "Unacademy", careersPage: "https://unacademy.com/careers" },
  { name: "UpGrad", careersPage: "https://www.upgrad.com/careers/" },
  { name: "Extramarks", careersPage: "https://www.extramarks.com/careers" },
  { name: "Vedantu", careersPage: "https://www.vedantu.com/careers" },
  { name: "Coursera", careersPage: "https://www.coursera.org/about/careers" },
  { name: "Edureka", careersPage: "https://www.edureka.co/careers" },
  { name: "Khan Academy", careersPage: "https://www.khanacademy.org/about/careers" },
  { name: "Teachmint", careersPage: "https://www.teachmint.com/careers" },
  { name: "Classplus", careersPage: "https://www.classplusapp.com/careers" },
  { name: "Simplilearn", careersPage: "https://www.simplilearn.com/careers" },
  { name: "Toppr", careersPage: "https://www.toppr.com/careers/" },
  { name: "Skillshare", careersPage: "https://www.skillshare.com/jobs" },
  { name: "Amazon", careersPage: "https://www.amazon.jobs/" },
  { name: "Flipkart", careersPage: "https://flipkartcareers.com" },
  { name: "Myntra", careersPage: "https://www.myntra.com/careers" },
  { name: "Snapdeal", careersPage: "https://www.snapdeal.com/careers" },
  { name: "Meesho", careersPage: "https://meesho.com/careers" },
  { name: "Noon", careersPage: "https://www.noon.com/careers" },
  { name: "Ajio", careersPage: "https://www.ajio.com/careers" },
  { name: "Nykaa", careersPage: "https://careers.nykaa.com" },
  { name: "OLX", careersPage: "https://www.olxgroup.com/careers" },
  { name: "Propertyfinder", careersPage: "https://www.propertyfinder.ae/en/careers" },
  { name: "Cars24", careersPage: "https://www.cars24.com/jobs" },
  { name: "Shopsy", careersPage: "https://shopsy.in/careers" },
  { name: "Urban Company", careersPage: "https://www.urbancompany.com/careers" },
  { name: "Swiggy", careersPage: "https://swiggy.com/careers" },
  { name: "Zomato", careersPage: "https://zomato.com/careers" },
  { name: "Dunzo", careersPage: "https://www.dunzo.com/careers" },
  { name: "Blinkit", careersPage: "https://blinkit.com/careers" },
  { name: "Grofers", careersPage: "https://www.grofers.com/careers" },
  { name: "Delhivery", careersPage: "https://v3.delhivery.com/careers" },
  { name: "Udaan", careersPage: "https://udaan.com/careers" },
  { name: "BookMyTrip", careersPage: "https://www.bookmytrip.com/careers" },
  { name: "Goibibo", careersPage: "https://www.goibibo.com/careers" },
  { name: "OYO Rooms", careersPage: "https://www.oyorooms.com/careers" },
  { name: "Uber", careersPage: "https://www.uber.com/global/en/careers/" },
  { name: "Ola", careersPage: "https://ola.careers" },
  { name: "Careem", careersPage: "https://careers.careem.com" },
  { name: "Dubizzle", careersPage: "https://dubizzle.com/careers" },
  { name: "Air Arabia", careersPage: "https://www.airarabia.com/en/careers" },
  { name: "Qatar Airways", careersPage: "https://careers.qatarairways.com" },
  { name: "Emirates", careersPage: "https://www.emiratesgroupcareers.com" },
  { name: "KPMG", careersPage: "https://home.kpmg/xx/en/home/careers.html" },
  { name: "McKinsey", careersPage: "https://www.mckinsey.com/careers" },
  { name: "Bain & Co.", careersPage: "https://www.bain.com/careers/" },
  { name: "Deloitte", careersPage: "https://www2.deloitte.com/global/en/careers.html" },
  { name: "PwC", careersPage: "https://www.pwc.com/gx/en/careers.html" },
  { name: "EY", careersPage: "https://www.ey.com/en_gl/careers" },
  { name: "Tiger Analytics", careersPage: "https://www.tigeranalytics.com/careers/" },
  { name: "Tredence", careersPage: "https://www.tredence.com/careers/" },
  { name: "Tower Research Capital", careersPage: "https://www.tower-research.com/careers" },
  { name: "Fractal Analytics", careersPage: "https://fractalanalytics.com/careers" },
  { name: "BCG (Boston Consulting)", careersPage: "https://www.bcg.com/careers" },
  { name: "Accenture", careersPage: "https://www.accenture.com/in-en/careers" },
  { name: "Novartis", careersPage: "https://www.novartis.com/careers" },
  { name: "PharmEasy", careersPage: "https://pharmeasy.in/careers" },
  { name: "Eli Lilly", careersPage: "https://careers.lilly.com" },
  { name: "GSK", careersPage: "https://www.gsk.com/en-gb/careers/" },
  { name: "Pfizer", careersPage: "https://www.pfizer.com/careers" },
  { name: "Healthkart", careersPage: "https://www.healthkart.com/careers" },
  { name: "Med Supply International", careersPage: "https://www.medsupplyinternational.com/careers/" },
  { name: "Sanofi", careersPage: "https://www.sanofi.com/en/careers" },
  { name: "Abbott", careersPage: "https://www.abbott.com/careers.html" },
  { name: "Roche", careersPage: "https://careers.roche.com/global/en.html" },
  { name: "Dunnhumby", careersPage: "https://www.dunnhumby.com/careers/" },
  { name: "Freshworks", careersPage: "https://www.freshworks.com/careers/" },
  { name: "Freshdesk", careersPage: "https://freshdesk.com/careers" },
  { name: "Zeta", careersPage: "https://www.zeta.in/careers" },
  { name: "BrowserStack", careersPage: "https://www.browserstack.com/careers" },
  { name: "Redington Gulf", careersPage: "https://redingtongulf.com/careers" },
  { name: "Friesland Campina", careersPage: "https://www.frieslandcampina.com/careers" },
  { name: "InMobi", careersPage: "https://www.inmobi.com/careers" },
  { name: "Akamai", careersPage: "https://www.akamai.com/careers" },
  { name: "Directi", careersPage: "https://www.directi.com/careers" },
  { name: "Arcesium", careersPage: "https://www.arcesium.com/careers" },
  { name: "Cohesity", careersPage: "https://www.cohesity.com/careers/" },
  { name: "Axtria", careersPage: "https://www.axtria.com/careers/" },
  // Logistics and Transportation
  { name: "Delhivery", careersPage: "https://www.delhivery.com/careers/" },
  { name: "Dunzo", careersPage: "https://www.dunzo.com/careers" },
  { name: "Uber", careersPage: "https://www.uber.com/us/en/careers/" },
  { name: "Ola", careersPage: "https://career.olacabs.com/" },
  { name: "Qatar Airways", careersPage: "https://careers.qatarairways.com/" },
  { name: "Emirates", careersPage: "https://www.emiratesgroupcareers.com/" },
  { name: "flydubai", careersPage: "https://careers.flydubai.com/" },
  { name: "Air Arabia", careersPage: "https://www.airarabia.com/en/careers" },
  { name: "Oman Air", careersPage: "https://www.omanair.com/gbl/en/careers" },
  { name: "British Airways", careersPage: "https://careers.ba.com/" },
  { name: "DP World", careersPage: "https://www.dpworld.com/careers" },
  { name: "Dubai Taxi Corporation", careersPage: "https://www.dubaitaxi.ae/careers" },
  { name: "Careem", careersPage: "https://careem.engineering/careers/" },
  // Media, Streaming, and Entertainment
  { name: "Disney+ Hotstar", careersPage: "https://careers.hotstar.com/" },
  { name: "Netflix", careersPage: "https://jobs.netflix.com/" },
  { name: "OSN", careersPage: "https://osncareer.osn.com/" },
  { name: "Zee5", careersPage: "https://www.zee.com/careers/" },
  { name: "Jio Saavn", careersPage: "https://www.jiosaavn.com/corporate/careers" },
  { name: "Gaana", careersPage: "https://gaana.com/careers" },
  { name: "Cricbuzz", careersPage: "https://www.cricbuzz.com/careers" },
  { name: "Junglee Games", careersPage: "https://junglee.games/careers/" },
  { name: "Dream11", careersPage: "https://careers.dream11.com/" },
  { name: "Hunger Station", careersPage: "https://hungerstation.com/careers" },
  { name: "TikTok", careersPage: "https://careers.tiktok.com/" },
  { name: "Dubizzle", careersPage: "https://dubizzle.applytojob.com/apply" },
  { name: "OMD UAE", careersPage: "https://www.omd.com/mena/careers/" },
  { name: "Spotify", careersPage: "https://www.spotifyjobs.com/" },
  { name: "YouTube", careersPage: "https://careers.google.com/teams/youtube/" },
  { name: "Facebook (Meta)", careersPage: "https://www.metacareers.com/" },
  // SaaS and Enterprise Software
  { name: "Atlassian", careersPage: "https://www.atlassian.com/company/careers" },
  { name: "HubSpot", careersPage: "https://www.hubspot.com/careers" },
  { name: "Intuit", careersPage: "https://careers.intuit.com" },
  { name: "Adobe", careersPage: "https://adobe.wd5.myworkdayjobs.com/en-US/careers" },
  { name: "Slack", careersPage: "https://slack.com/careers" },
  { name: "Flock", careersPage: "https://www.flock.com/careers" },
  { name: "Zoom", careersPage: "https://zoom.us/careers" },
  { name: "Freshworks", careersPage: "https://www.freshworks.com/company/careers/" },
  { name: "Shopify", careersPage: "https://www.shopify.com/careers" },
  { name: "Sendinblue", careersPage: "https://www.sendinblue.com/jobs/" },
  { name: "Sprinklr", careersPage: "https://www.sprinklr.com/careers/" },
  { name: "Sumologic", careersPage: "https://www.sumologic.com/company/careers/" },
  { name: "Cohesity", careersPage: "https://www.cohesity.com/company/careers/" },
  { name: "Gainsight", careersPage: "https://www.gainsight.com/careers/" },
  { name: "Salesforce", careersPage: "https://www.salesforce.com/company/careers/" },
  { name: "Snowflake", careersPage: "https://careers.snowflake.com" },
  { name: "Zendesk", careersPage: "https://www.zendesk.com/jobs/" },
]; 